### ISSUE TITLE
Automatically generate route name

### ISSUE THREAD

**Issue by Dimitar5555** [osmandapp/OsmAnd#17789]
# 🚀 feature request

### Description

Currently PT routes will show only their `ref` if `name` is not present.

The screenshot is taken from https://www.openstreetmap.org/node/10744861347.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/19364673/c3577f59-9b5b-44c6-808e-360eca9a2cbf"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe the solution you'd like

Generating names like iD editor does it should work.

https://github.com/openstreetmap/iD/pull/8276/files

```
display_name:
      direction: "{direction}"
      from_to: "from {from} to {to}"
      from_to_via: "from {from} to {to} via {via}"
      network_direction: "{network} {direction}"
      network_from_to: "{network} from {from} to {to}"
      network_from_to_via: "{network} from {from} to {to} via {via}"
      ref: "{ref}"
      ref_direction: "{ref} {direction}"
      ref_from_to: "{ref} from {from} to {to}"
      ref_from_to_via: "{ref} from {from} to {to} via {via}"
      network_ref: "{network} {ref}"
      network_ref_direction: "{network} {ref} {direction}"
      network_ref_from_to: "{network} {ref} from {from} to {to}"
      network_ref_from_to_via: "{network} {ref} from {from} to {to} via {via}"
```

### Describe alternatives you've considered

The only workaround is to add a name, but there is not much point in duplicating the data that is already available in machine readable format.

**Comment by vshcherb** [comment]
It's not clear in which order should we apply the rules:
```
display_name:
      direction: "{direction}"
      from_to: "from {from} to {to}"
      from_to_via: "from {from} to {to} via {via}"
```

In order they are mentionned they won't work as 3rd option wouldn't make sense as it will be always captured by 2nd option, may be they are applied in reverse order
